### ISSUE TITLE
Works great!

### ISSUE THREAD

**Issue by agwells** [my2iu/TADS2-html5#1]
Hi,

I found this project last week, and I just wanted to say that it's brilliant! :) I used it to play "The Legend Lives!" and "The Horror of Rylvania" all the way through, on Android Chrome on my not-very-powerful Android 5 phone. The only issues I noticed were:

1. Slow startup time, which I can see you're already aware of, from the git logs. And of course there's not a whole lot that can be done about that.

2. Can't load the same save-game file twice in a row. That is, if I load "game5.sav", then play a few turns, then decide I want to go back to that savepoint, so I try to load "games5.sav" a second time. On the second time, nothing happens. It will work if I load a different save-game file first; e.g. load "game5.sav", then load "game7.sav", then load "game5.sav".

3. Couldn't view the end-game text of Rylvania. I suspect this is a bug in handling the situation where a game auto-quits itself when you win. I could view the end-game text of "The Legend Lives!" just fine, though.

4. Could not load "The Legend Lives!". The other games I tried (all the ones from [adventions.zip](http://ifdb.tads.org/viewgame?id=bi8rb6cieq8p05wl)) loaded fine, but "The Legend Lives!" caused a crash with the error message "RangeError: Maximum call stack size exceeded Traceback". I was eventually able to solve this by recompiling with optimization level "-O1".

My copy of the project, with the -O1 and a few other changes, is here: https://github.com/agwells/TADS2-html5 . The changes I've made are:
- porting the build scripts to Linux
- adding optimization level -O1
- allow savegame files with any name
- put a limit on the scrollback size, to improve performance

I don't know if any of those are particularly useful changes, but feel free to take a look at the commit list and use any of my changes if you think they're helpful.

Cheers!
Aaron

**Comment by my2iu** [comment]
Awesome. I'll take a closer look at this stuff on the weekend. For point 3, I imagine the problem is that I buffer the output (so that I can parse the HTML in HTMLTADS), but I don't properly flush things if a game exits without asking for any user input. I'll dig into that later on.

**Comment by agwells** [comment]
Here are some help files for testing out the game-ending. It's a copy of Rylvania, and a save file from right before the ending. Just restore it and do `inject me with needle` to trigger the ending.

[rylvania-ending.zip](https://github.com/my2iu/TADS2-html5/files/1601770/rylvania-ending.zip)

I tested it out just now and it seems the difference between Rylvania and Legend Lives, is that Rylvania ends by quitting the interpreter (after displaying the victory text), while Legend Lives ends with a "Restore, Restart, Quit" prompt. So you're probably right about the cause.

**Comment by my2iu** [comment]
Actually, I'll have to put the project on hold for a while. The project requires SharedArrayBuffer support in web browsers, but all web browsers removed that feature yesterday due to the latest security scare. There is currently no timeline for when that SharedArrayBuffers support will be reenabled, so everything will have to wait until then.

**Comment by agwells** [comment]
Lol, well, I feel lucky I found it and got to replay all those Adventions games the week _before_ Meltdown and Specter hit!

I'll go ahead and close this issue for now, and open a separate one to document the SharedArrayBuffer problem.

**Comment by my2iu** [comment]
I've adjusted the build scripts to generate WebAssembly instead of asm.js. That seems to fix 4 (asm.js has always been a little buggy), and makes 1 more bearable. I've also gone in and fixed 2 and 3.
